version: '3.8'

services:
  app:
    image: protekauto-cms:latest
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - stack.env
    volumes:
      - uploads:/app/public/uploads

volumes:
  uploads:
    driver: local
  node_modules:
    driver: local
  next-cache:
    driver: local 