version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - stack.env
    volumes:
      - uploads:/app/public/uploads
      - node_modules:/app/node_modules
      - next-cache:/app/.next

volumes:
  uploads:
    driver: local
  node_modules:
    driver: local
  next-cache:
    driver: local 